# apiVersion: v1
# kind: Secret
# metadata:
#   name: telegraf-secret
# type: Opaque
# stringData:
#   INFLUXDB_USER: influxdb
#   INFLUXDB_USER_PASSWORD: influxdb
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      name: telegraf-pod
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf
        imagePullPolicy: Never
        volumeMounts:
        - name: docker-unix-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-unix-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
