apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: wordpress
    targetPort: 5050
  externalTrafficPolicy: Cluster
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress
        livenessProbe:
          exec:
            command:
              - sh
              - healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 10
